"""Markdown reporter: generates `.ai-inventory.md` for committing to the repo.

This artifact serves two purposes:
  1. Documentation in the repo — anyone browsing the repo sees the AI surfaces.
  2. Diff baseline for the GitHub Action — PRs compare new scan against this file.
"""
from __future__ import annotations

from typing import Dict, List

from ..cross_promo import build_upgrade_url, headline_finding, specialists_for_report
from ..types import (
    CATEGORY_AGENT_FRAMEWORK,
    CATEGORY_AI_INFRA,
    CATEGORY_ENV_KEY,
    CATEGORY_LLM_SDK,
    CATEGORY_MCP_SERVER,
    CATEGORY_MODEL_GATEWAY,
    Finding,
    Report,
)


CATEGORY_HEADING: Dict[str, str] = {
    CATEGORY_LLM_SDK: "LLM SDK Call Sites",
    CATEGORY_AGENT_FRAMEWORK: "Agent Frameworks",
    CATEGORY_MCP_SERVER: "MCP Servers",
    CATEGORY_MODEL_GATEWAY: "Model Gateways",
    CATEGORY_AI_INFRA: "AI Infrastructure",
    CATEGORY_ENV_KEY: "AI Provider API Keys (env)",
}

CATEGORY_ORDER: List[str] = [
    CATEGORY_LLM_SDK,
    CATEGORY_AGENT_FRAMEWORK,
    CATEGORY_MCP_SERVER,
    CATEGORY_MODEL_GATEWAY,
    CATEGORY_AI_INFRA,
    CATEGORY_ENV_KEY,
]


def render_markdown(report: Report) -> str:
    """Render `report` as a markdown document suitable for committing."""
    out: List[str] = []
    out.append("# AI Inventory")
    out.append("")
    out.append(
        f"> Generated by [ai-surface](https://github.com/apisec-inc/ai-surface) "
        f"v{report.tool_version}. Schema {report.schema_version}."
    )
    out.append(f"> Scan timestamp: `{report.scan_timestamp}`")
    out.append("")

    surface_count = len(report.findings)
    risk_count = sum(len(f.risk_indicators) for f in report.findings)
    out.append(
        f"**Production AI surfaces:** {surface_count}  "
        f"·  **Risk indicators:** {risk_count}"
    )
    out.append("")

    if not report.findings:
        out.append("No production AI surfaces detected at scan time.")
        out.append("")
        _append_footer(out, report)
        return "\n".join(out)

    by_cat = report.by_category()
    for cat in CATEGORY_ORDER:
        if cat in by_cat and by_cat[cat]:
            _append_category(out, cat, by_cat[cat])

    # Forward compatibility for unknown categories
    for cat, findings in by_cat.items():
        if cat not in CATEGORY_ORDER:
            _append_category(out, cat, findings)

    _append_risk_summary(out, report)
    _append_footer(out, report)
    return "\n".join(out)


def _append_category(out: List[str], category: str, findings: List[Finding]) -> None:
    heading = CATEGORY_HEADING.get(category, category.replace("-", " ").title())
    out.append(f"## {heading}")
    out.append("")
    for finding in findings:
        _append_finding(out, finding)
    out.append("")


def _append_finding(out: List[str], finding: Finding) -> None:
    out.append(f"### {finding.surface}")
    out.append("")

    if finding.evidence and finding.evidence.files:
        files = finding.evidence.files
        if len(files) <= 5:
            file_list = ", ".join(f"`{f}`" for f in files)
        else:
            file_list = ", ".join(f"`{f}`" for f in files[:3]) + f", and {len(files) - 3} more"
        out.append(f"**Files:** {file_list}")
        out.append("")

    if finding.permissions:
        perms = ", ".join(f"`{p}`" for p in finding.permissions)
        out.append(f"**Tools/permissions:** {perms}")
        out.append("")

    models = finding.evidence.metadata.get("models_used") if finding.evidence else None
    if models:
        models_str = ", ".join(f"`{m}`" for m in models)
        out.append(f"**Models:** {models_str}")
        out.append("")

    if finding.risk_indicators:
        out.append("**Risk indicators:**")
        out.append("")
        for risk in finding.risk_indicators:
            out.append(f"- ⚠️ {risk}")
        out.append("")
        # Inline per-finding deep link to APIsec validation, with finding context.
        url = build_upgrade_url(finding, source="ai-surface", medium="markdown")
        out.append(f"[Validate this surface →]({url})")
        out.append("")

    if finding.evidence and finding.evidence.snippet:
        snippet = finding.evidence.snippet.strip()
        if snippet:
            out.append("```")
            out.append(snippet)
            out.append("```")
            out.append("")


def _append_risk_summary(out: List[str], report: Report) -> None:
    risks = report.all_risk_indicators()
    if not risks:
        return
    out.append("## Risk Indicator Summary")
    out.append("")
    for r in risks:
        out.append(f"- ⚠️ {r}")
    out.append("")


def _append_footer(out: List[str], report: Report) -> None:
    out.append("---")
    out.append("")

    # Lateral cross-promotion to OSS specialists (mcp-audit, etc.) for the
    # categories present in the report. Only renders shipped specialists.
    specialists = specialists_for_report(report.findings)
    for spec in specialists:
        out.append(f"- {spec['tagline'].capitalize()}: [{spec['tool']}]({spec['url']})")
    if specialists:
        out.append("")

    headline = headline_finding(report.findings)
    upgrade_url = build_upgrade_url(headline, source="ai-surface", medium="markdown")
    out.append(
        "Validate which of these surfaces are exploitable in a running application: "
        f"[apisec.ai/ai-validation]({upgrade_url})"
    )
    out.append("")
